package models

type Binary string
type BinaryRm string
type Bytes string
type BytesRm string
type Date string
type DateRm string
type DateTime string
type DateTimeRm string
type DiameterIdentity string
type DiameterIdentityRm string
type Double float64
type DoubleRm float64
type DurationSec int64
type DurationSecRm int64
type Float float64
type FloatRm float64
type Uint16 uint16
type Uint16Rm uint16
type Int32 int32
type Int32Rm int32
type Int64 int64
type Int64Rm int64
type Ipv4Address string
type Ipv4AddressRm string
type Ipv6Address string
type Ipv6AddressRm string
type Ipv6Prefix string
type Ipv6PrefixRm string
type MacAddr48 string
type MacAddr48Rm string
type SupportedFeatures string
type Uinteger uint64
type UintegerRm uint64
type Uint32 uint32
type Uint32Rm uint32
type Uint64 uint64
type Uint64Rm uint64
type Uri string
type UriRm string
type VarUeId string
type VarUeIdRm string
type TimeZone string
type TimeZoneRm string
